export const COUNTRIES = [
  { name: 'United States', code: 'US', currency: 'USD' },
  { name: 'United Kingdom', code: 'GB', currency: 'GBP' },
  { name: 'Sri Lanka', code: 'LK', currency: 'LKR' },
  { name: 'India', code: 'IN', currency: 'INR' },
  { name: 'Australia', code: 'AU', currency: 'AUD' },
  { name: 'Canada', code: 'CA', currency: 'CAD' },
  { name: 'Germany', code: 'DE', currency: 'EUR' },
  { name: 'France', code: 'FR', currency: 'EUR' },
  { name: 'Japan', code: 'JP', currency: 'JPY' },
  { name: 'China', code: 'CN', currency: 'CNY' },
  { name: 'Singapore', code: 'SG', currency: 'SGD' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'AED' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'SAR' },
  { name: 'Switzerland', code: 'CH', currency: 'CHF' },
  { name: 'Sweden', code: 'SE', currency: 'SEK' },
  { name: 'Norway', code: 'NO', currency: 'NOK' },
  { name: 'Denmark', code: 'DK', currency: 'DKK' },
  { name: 'Netherlands', code: 'NL', currency: 'EUR' },
  { name: 'Italy', code: 'IT', currency: 'EUR' },
  { name: 'Spain', code: 'ES', currency: 'EUR' },
  { name: 'Brazil', code: 'BR', currency: 'BRL' },
  { name: 'Mexico', code: 'MX', currency: 'MXN' },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR' },
  { name: 'New Zealand', code: 'NZ', currency: 'NZD' },
  { name: 'South Korea', code: 'KR', currency: 'KRW' },
  { name: 'Hong Kong', code: 'HK', currency: 'HKD' },
  { name: 'Malaysia', code: 'MY', currency: 'MYR' },
  { name: 'Thailand', code: 'TH', currency: 'THB' },
  { name: 'Indonesia', code: 'ID', currency: 'IDR' },
  { name: 'Pakistan', code: 'PK', currency: 'PKR' },
  { name: 'Bangladesh', code: 'BD', currency: 'BDT' },
  { name: 'Russia', code: 'RU', currency: 'RUB' },
  { name: 'Turkey', code: 'TR', currency: 'TRY' },
  { name: 'Israel', code: 'IL', currency: 'ILS' },
  { name: 'Egypt', code: 'EG', currency: 'EGP' },
  { name: 'Nigeria', code: 'NG', currency: 'NGN' },
  { name: 'Kenya', code: 'KE', currency: 'KES' },
  { name: 'Vietnam', code: 'VN', currency: 'VND' },
  { name: 'Philippines', code: 'PH', currency: 'PHP' },
  { name: 'Ireland', code: 'IE', currency: 'EUR' },
  { name: 'Portugal', code: 'PT', currency: 'EUR' },
  { name: 'Greece', code: 'GR', currency: 'EUR' },
  { name: 'Austria', code: 'AT', currency: 'EUR' },
  { name: 'Belgium', code: 'BE', currency: 'EUR' },
  { name: 'Finland', code: 'FI', currency: 'EUR' },
  { name: 'Poland', code: 'PL', currency: 'PLN' },
  { name: 'Czech Republic', code: 'CZ', currency: 'CZK' },
  { name: 'Hungary', code: 'HU', currency: 'HUF' },
  { name: 'Romania', code: 'RO', currency: 'RON' },
  { name: 'Ukraine', code: 'UA', currency: 'UAH' },
  { name: 'Chile', code: 'CL', currency: 'CLP' },
  { name: 'Colombia', code: 'CO', currency: 'COP' },
  { name: 'Argentina', code: 'AR', currency: 'ARS' },
  { name: 'Peru', code: 'PE', currency: 'PEN' },
].sort((a, b) => a.name.localeCompare(b.name));

export const CURRENCIES = [
  { name: 'US Dollar', code: 'USD' },
  { name: 'Euro', code: 'EUR' },
  { name: 'British Pound', code: 'GBP' },
  { name: 'Sri Lankan Rupee', code: 'LKR' },
  { name: 'Indian Rupee', code: 'INR' },
  { name: 'Australian Dollar', code: 'AUD' },
  { name: 'Canadian Dollar', code: 'CAD' },
  { name: 'Japanese Yen', code: 'JPY' },
  { name: 'Chinese Yuan', code: 'CNY' },
  { name: 'Singapore Dollar', code: 'SGD' },
  { name: 'UAE Dirham', code: 'AED' },
  { name: 'Saudi Riyal', code: 'SAR' },
  { name: 'Swiss Franc', code: 'CHF' },
  { name: 'Swedish Krona', code: 'SEK' },
  { name: 'Norwegian Krone', code: 'NOK' },
  { name: 'Danish Krone', code: 'DKK' },
  { name: 'Brazilian Real', code: 'BRL' },
  { name: 'Mexican Peso', code: 'MXN' },
  { name: 'South African Rand', code: 'ZAR' },
  { name: 'New Zealand Dollar', code: 'NZD' },
  { name: 'South Korean Won', code: 'KRW' },
  { name: 'Hong Kong Dollar', code: 'HKD' },
  { name: 'Malaysian Ringgit', code: 'MYR' },
  { name: 'Thai Baht', code: 'THB' },
  { name: 'Indonesian Rupiah', code: 'IDR' },
  { name: 'Pakistani Rupee', code: 'PKR' },
  { name: 'Bangladeshi Taka', code: 'BDT' },
  { name: 'Russian Ruble', code: 'RUB' },
  { name: 'Turkish Lira', code: 'TRY' },
  { name: 'Israeli New Shekel', code: 'ILS' },
  { name: 'Egyptian Pound', code: 'EGP' },
  { name: 'Nigerian Naira', code: 'NGN' },
  { name: 'Kenyan Shilling', code: 'KES' },
  { name: 'Vietnamese Dong', code: 'VND' },
  { name: 'Philippine Peso', code: 'PHP' },
  { name: 'Polish Zloty', code: 'PLN' },
  { name: 'Czech Koruna', code: 'CZK' },
  { name: 'Hungarian Forint', code: 'HUF' },
  { name: 'Romanian Leu', code: 'RON' },
  { name: 'Ukrainian Hryvnia', code: 'UAH' },
  { name: 'Chilean Peso', code: 'CLP' },
  { name: 'Colombian Peso', code: 'CO' },
  { name: 'Argentine Peso', code: 'ARS' },
  { name: 'Peruvian Sol', code: 'PEN' },
].sort((a, b) => a.name.localeCompare(b.name));
